base_dir: /opt
system_user_name: root
access_type: VSK
state_name: HR
local_ipv4_address: 10.0.0.1
mode_of_installation: public
storage_type: local
api_endpoint: localhost
google_analytics_tracking_id: NA
db_user: cqube_user
db_name: cqube
db_password: cQube@123
read_only_db_user: cqube_db_user
read_only_db_password: cQube@123
keycloak_adm_name: admin
keycloak_adm_password: Admin@123
